### ISSUE TITLE
Enemy(ies)

### ISSUE THREAD

**Issue by NolSpencer** [NolSpencer/GameProgrammingProject2022#10]
- [x] #44
- [ ] Display Health above enemy?
- [x] model/models?
- [x] #41
- [ ] Ability/Abilities? Note: Maybe since they are blobs we make it so if you are in a certain environment that blob takes of "stats" of its environment.
- [ ] How will they damage the player? Ranged/Melee?
- [x] #42
- [ ] Boss and boss AI. Maybe a boss fight scene, so add different UI for that boss scene.
- [x] #43

**Comment by jsakal** [comment]
Some of these got spun into their own issue, while some were just out of scope
