### ISSUE TITLE
Weapons

### ISSUE THREAD

**Issue by NolSpencer** [NolSpencer/GameProgrammingProject2022#11]
- [ ] Melee?
- [x] Ranged?
- [x] Models
- [ ] Projectile bullets
- [x] Animations for both guns and melee
- [ ] bullet models
- [ ] Shields?
- [ ] if the blobs shoot at you could we do a reflective shield maybe?

**Comment by jsakal** [comment]
A lot of this was out of scope, ended up using raycast instead of projectiles, no melee, etc.
