### ISSUE TITLE
The World and Environment

### ISSUE THREAD

**Issue by NolSpencer** [NolSpencer/GameProgrammingProject2022#12]
- [x] Basic world environment for testing.
- [ ] Procedural generation?
- [ ] Dungeons?
- [ ] Boss room?
- [x] Npc's?
- [ ] A town? roads? animals? Trees? 
- [x] Shops/Stores?
- [x] Money System?
- [ ] A story?
- [x] mountains? plains? Caves? hills?
- [ ] Night/Daytime cycle?

**Comment by NolSpencer** [comment]
Need to talk and figure out what we want it to look like.

**Comment by jsakal** [comment]
Some of these ended up being out of scope for the project.
