### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by brendontn16** [NolSpencer/GameProgrammingProject2022#7]

**Comment by brendontn16** [comment]
https://assetstore.unity.com/packages/3d/props/exterior/rock-and-boulders-2-6947
https://assetstore.unity.com/packages/3d/props/guns/guns-pack-low-poly-guns-collection-192553
https://assetstore.unity.com/packages/3d/props/weapons/free-stylized-weapons-216047
https://assetstore.unity.com/packages/3d/animations/free-32-rpg-animations-215058
https://assetstore.unity.com/packages/3d/animations/melee-warrior-animations-free-165785
https://assetstore.unity.com/packages/3d/animations/basic-motions-free-154271
https://assetstore.unity.com/packages/tools/gui/3d-modern-menu-ui-116144
https://www.gameuidatabase.com/
https://www.cgtrader.com/blog/gear-up-for-game-jam-2018-with-these-free-3d-models-2018-01

**Comment by jsakal** [comment]
Everyone added some amount of assets over the course of the project, not really at any specific time
